name = "Bombermons"
author = "Bomber and Jeef"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "987a0f6dd8efbbd491470e9de750ba50d798da450a0e36555b0a7d37c84bf43e"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
